### ISSUE TITLE
create_server.rb:141:in `block in call': undefined method `server=' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by FlxPeters** [cloudbau/vagrant-openstack-plugin#101]
Hi,

i'm trying to launch an instance to my OpenStack build with Fuel OpenStack via Vagrant (1.7.2).
I just installed the plugin via vagrant, so this should be the newest Version.

The Instance comes up in OpenStack, but when it tires to assign a floating IP i get an error (Even does not work with an unassigned floating IP set):

```
$ vagrant up --provider=openstack
Bringing machine 'default' up with 'openstack' provider...
==> default: Finding flavor for server...
==> default: Finding image for server...
==> default: Finding network for server...
==> default: options[:nics]: [{:net_id=>"1361df7e-b944-40e7-92c0-853b47b30bc2"}]
==> default: Launching a server with the following settings...
==> default:  -- Flavor: m1.micro
==> default:  -- Image: TestVM
==> default:  -- Name: default
==> default:  -- Network: net04
==> default: Waiting for the server to be built...
Progress: 0%==> default: Using floating IP :auto
/Users/fpeters/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.11.1/lib/vagrant-openstack-plugin/action/create_server.rb:141:in `block in call': undefined method `server=' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/retryable.rb:17:in `retryable'
	from /Users/fpeters/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.11.1/lib/vagrant-openstack-plugin/action/create_server.rb:103:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/fpeters/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.11.1/lib/vagrant-openstack-plugin/action/create_orchestration_stack.rb:21:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/fpeters/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.11.1/lib/vagrant-openstack-plugin/action/connect_openstack.rb:73:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/set_hostname.rb:16:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/fpeters/.vagrant.d/gems/gems/vagrant-openstack-plugin-0.11.1/lib/vagrant-openstack-plugin/action/sync_folders.rb:18:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/fpeters/.vagrant.d/gems/gems/vagrant-cachier-1.1.0/lib/vagrant-cachier/action/install_buckets.rb:14:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/fpeters/.vagrant.d/gems/gems/vagrant-cachier-1.1.0/lib/vagrant-cachier/action/configure_bucket_root.rb:20:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
fpeters at Felixs-MacBook-Pro-2.local  ~/projects/tests/openstack
```

Vagrantfile:
```
require 'vagrant-openstack-plugin'

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"

  # Make sure the private key from the key pair is provided
  config.ssh.private_key_path = "~/.ssh/id_rsa"

  config.vm.provider :openstack do |os|
    os.username     = "admin"          # e.g. "#{ENV['OS_USERNAME']}"
    os.api_key      = "admin"           # e.g. "#{ENV['OS_PASSWORD']}"
    os.flavor       = /m1.micro/                # Regex or String
    os.image        = /TestVM/                 # Regex or String
    os.endpoint     = "http://172.16.0.2:5000/v2.0/tokens"      # e.g. "#{ENV['OS_AUTH_URL']}/tokens"
    os.keypair_name = "MAcbook"      # as stored in Nova
    os.ssh_username = "cirros"           # login for the VM

    #os.metadata  = {"key" => "value"}                      # optional
    #os.user_data = "#cloud-config\nmanage_etc_hosts: True" # optional
    os.network            = "net04"            # optional
    os.networks           = [ "net04" ]     # optional, overrides os.network
    #os.address_id         = "YOUR ADDRESS ID"              # optional (`network` above has higher precedence)
    #os.scheduler_hints    = {
    #    :cell => 'australia'
    #}                                          # optional
    #os.availability_zone  = "nova"           # optional
    #os.security_groups    = ['default']    # optional
    os.tenant             = "admin" # optional
    os.floating_ip        = ":auto"      # optional (The floating IP to assign for this instance, or set to :auto)
    os.floating_ip_pool   = "net04_ext"           # optional (The floating IP pool to allocate addresses from, if floating_ip = :auto)

  end
end
```

**Comment by Chealion** [comment]
Having been bitten by this as well and just in case anyone else runs into this issue:

floating_ip should be set to :auto without any quotes.

    os.floating_ip = :auto
